apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  labels:
    app: go-deployment
  name: go-deployment
spec:
  replicas: 6
  selector:
    matchLabels:
      app: go-deployment
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: go-deployment
    spec:
      containers:
      - image: httpd
        name: httpd
        ports:
        - containerPort: 80
        resources: {}
status: {}
